# Generated by Django 4.0.5 on 2022-06-09 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(choices=[('Assignment', 'Assignment'), ('Content', 'Content'), ('Admission', 'Admission'), ('Argumentative', 'Argumentative'), ('Article', 'Article Writing'), ('Movie', 'Movie Review'), ('Business', 'Business Plan'), ('Capstone', 'Capstone Project'), ('Case', 'Case Study'), ('Coursework', 'Coursework'), ('Creative', 'Critical Thinking')], max_length=100)),
                ('level', models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('M', 'Masters'), ('D', 'Doctoral')], max_length=10)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('AW', 'Academic Writing'), ('EP', 'Editting & Proofreading')], max_length=100)),
                ('subject', models.CharField(choices=[('Biology', 'Biology'), ('Mathematics', 'Mathematics'), ('Economics', 'Economics')], max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='assignment/')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('end_date', models.DateField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.calculateprice')),
            ],
        ),
    ]
